pizza/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    # login is a standard form provided by django (it is customised using crispy forms)
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # logout is also handled by django
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('orders.urls')),
    path('', include('shopping_cart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (add_to_cart, delete_from_cart, order_details, checkout, success, update_transaction_records)

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name="purchase_success"),
    #url(r'^success/$', success, name='purchase_success'),
    path('item/delete/<int:item_id>/', delete_from_cart, name="delete_item"),
    #url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    path('checkout/', checkout, name="checkout"),
    path('update-transaction/<str:token>/', update_transaction_records, name='update_records'),
]

shopping_cart/models.py
from __future__ import unicode_literals
from django.db import models
from users.models import Cart
from orders.models import Item

# Create your models here.

class OrderItem(models.Model):
    item = models.OneToOneField(Item, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return str(self.item)


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.item.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

shopping_cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from users.models import Cart
from orders.models import Item
from shopping_cart.extras import generate_order_id
from shopping_cart.models import OrderItem, Order, Transaction
import datetime
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.

def get_user_pending_order(request):
    # get order for the correct user
    user_cart = get_object_or_404(Cart, user=request.user)
    order = Order.objects.filter(owner=user_cart, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request):
    # get the user cart
    user_cart = get_object_or_404(Cart, user=request.user)
    # filter items by latest
    item = Item.objects.filter(user=request.user).order_by('timestamp').last()

    # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(item=item)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_cart, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.success(request, "Item added to cart!")
    context = {
        'title': 'Cart'
    }
    return redirect('shopping_cart:order_summary')


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted!")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order,
        'title': 'Cart'
    }
    return render(request, 'shopping_cart/order_summary.html', context)


@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        try:
            token = request.POST['stripeToken']
            charge = stripe.Charge.create(amount=int(100*existing_order.get_cart_total()), currency='usd', description='Example charge', source=token)
            return redirect(reverse('shopping_cart:update_records', kwargs={'token': token}))
        except stripe.CardError as e:
            messages.warning(request, "Your card has been declined.")

    context = {
        'order': existing_order,
        'STRIPE_PUBLISHABLE_KEY': publishKey,
        'title': 'Checkout'
    }
    return render(request, 'shopping_cart/checkout.html', context)


@login_required()
def update_transaction_records(request, token):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()
    
    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # add products to user cart
    user_cart = get_object_or_404(Cart, user=request.user)
    # get the products from the items
    order_products = [item.item for item in order_items]
    user_cart.item.add(*order_products)
    user_cart.save()

    # create a transaction
    transaction = Transaction(cart=request.user.cart, token=token, order_id=order_to_purchase.id, amount=order_to_purchase.get_cart_total(), success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()

    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.success(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('orders-history'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/purchase_success.html', {})

shopping_cart/templates/shopping_cart/checkout.html
{% extends 'orders/base.html' %}
{% load static %}
{% block content %}
    <div class="content-section">
        <table class="table">
            <tr>
                <td colspan="2"><h4>Order Summary</h4></td>
            </tr>
            <tr>
                <td>
                    {% for item in order.get_cart_items %}
                        <tr>
                            <td>{{ item.item.size }} {{ item.item.meal_type }}</td>
                            <td>${{ item.item.price }}</td>
                        </tr>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                {% if order.get_cart_total != None %}
                    <td>
                        <strong class="pull-right">Order Total:</strong>
                    </td>
                    <td>
                        $<strong>{{ order.get_cart_total }}</strong>
                    </td>
                {% endif %}
            </tr>
        </table>
    </div>
    <div>
        <script src="https://js.stripe.com/v3/"></script>
        <form action="." method="post" id="payment-form" class="stripe-form">
            {% csrf_token %}
            <div style="margin: 10px;">
                <div class="stripe-form-row">
                    <label class="stripe-label" for="card-element">
                        Credit or debit card
                    </label>
                    <div id="card-element" class="StripeElement StripeElement--empty">
                        <div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; 
                                    display: block !important; background: transparent !important; position: relative !important; 
                                    opacity: 1 !important;">
                            <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame3" allowpaymentrequest="true" 
                                    src="https://js.stripe.com/v3/elements-inner-card-8a434729e4eb82355db4882974049278.html#style[base][color]=
                                        %2332325d&amp;style[base][lineHeight]=18px&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+
                                        sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base]
                                        [::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=
                                        %23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;features[noop]=false&amp;origin=
                                        https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js%2Felements%2Fquickstart&amp;
                                        controllerId=__privateStripeController0" title="Secure payment input frame" style="border: none !important; 
                                        margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; 
                                        overflow: hidden !important; display: block !important; height: 18px;"></iframe>
                            <input class="__PrivateStripeElement-input" aria-hidden="true" style="border: none !important; display: block !important; 
                                            position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; 
                                            padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; 
                                            background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                            <input class="__PrivateStripeElement-safariInput" aria-hidden="true" tabindex="-1" style="border: none !important; 
                                            display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; 
                                            left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; 
                                            opacity: 0 !important; background: transparent !important; pointer-events: none !important; 
                                            font-size: 16px !important;">
                        </div>
                    </div>
                    <!-- Used to display form errors. -->
                    <div id="card-errors" role="alert"></div>
                </div>
                <input type="hidden" id="nonce" name="payment_method_nonce">
            </div>
            <button class="stripe-button">Submit Payment</button>
        </form>
    </div>
    <div>
        </br>
        <p>For testing purposes the folowing card details can be entered:</p>
        <strong>Number: </strong>4242 4242 4242 4242</br>
        <strong>Expiry Date: </strong>Any date in the future</br>
        <strong>CVC: </strong>Any 3 numbers</br>
        <strong>ZIP: </strong>Any 5 numbers</br>
    </div>
    <div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div>
    
    <script src="{% static 'orders/checkout.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

{% endblock content %}

shopping_cart/templates/shopping_cart/order_summary.html
{% extends 'orders/base.html' %}
{% block content %}
    <table class="table table-hover table-bordered text-center">
        <tr class="text-center">
            <th>No.</th>
            <th>Item</th>
            <th>Price</th>
        </tr>
        {% for item in order.get_cart_items %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    {{ item.item.size }} {{ item.item.meal_type }}
                    <span class="float-right">
                        <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" 
                            class="text-danger" onclick="return confirm_delete();">
                            <i class="fas fa-trash"></i>
                        </a>
                    </span>
                </td>
                <td>${{ item.item.price }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3"> You have not added any items yet.</td>
            </tr>
        {% endfor %}
        <tr>
            {% if order.get_cart_total != None %}
                <td colspan="2">
                    <strong class="pull-right">Order Total:</strong>
                </td>
                <td colspan="1">
                    $<strong>{{ order.get_cart_total }}</strong>
                </td>
            {% endif %}
        </tr>
        <tr>
            <td colspan="1">
                <a href="{% url 'orders-create' %}" class="btn btn-warning pull-left">
                    {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
                </a>
            </td>
            <td colspan="2">
                {% if order.get_cart_items %}
                    <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
                {% endif %}
            </td>
        </tr>
    </table>
    <script>
        function confirm_delete() {
            return confirm("Do you want to remove this item from cart?");
        }
    </script>
{% endblock content %}